Julian qui sait pas utiliser git
Bonk-Corporation/ft_transcendence pull request #20
Opened 2024-04-29 19:41 UTC by demostanis

on peut pas encore merge parce que faut que jregle des conflits avec tailwind, mais au moins on peut rebase

2024-04-29 20:02 UTC, demostanis commented
cette pr etait degueu franchement julian
la prochaine fois c'est toi qui rebase

2024-04-29 20:12 UTC, demostanis commented
ça merge

2024-04-29 20:43 UTC, DinoMalin commented
Des heures entières pour parvenir à faire un rebase qui merge pas et c moi qui sait pas utiliser git

2024-04-29 22:41 UTC, demostanis commented
kestu raconte ça rebase

2024-04-30 18:01 UTC, acasamit requested changes
Everything disappears when we move something with the mouse or when we switch tabs in Firefox. In the profile section, consider adding some text to provide context (friend, game history, etc.). Additionally, cgodard asks you to consider using ApexCharts for the game statistics.

2024-05-02 16:04 UTC, merged