prod
Bonk-Corporation/ft_transcendence pull request #62
Opened 2024-06-05 01:14 UTC by demostanis

ft-transcendence.fr

2024-06-05 01:22 UTC, DinoMalin requested changes
Le chat a tjrs le bug

2024-06-05 13:16 UTC, demostanis commented
DinoMalin: tas test la PR ou ft-transcendence.fr directement? jsuis pas sur davoir mis le fix du chat sur ft-transcendence.fr

2024-06-05 13:28 UTC, DinoMalin commented
ft-transcendence.fr

2024-06-06 01:10 UTC, DinoMalin approved these changes

2024-06-06 01:11 UTC, DinoMalin commented
oui

2024-06-06 10:09 UTC, BolvicBolvicovic approved these changes
Yep

2024-06-06 10:12 UTC, merged